required-players: 2
countdown-seconds: 30
lobby-spawn:
  world: 'world'
  x: 100
  y: 100
  z: 100
  yaw: 180
  pitch: 180
arenas:
  0:
    world: 'world'
      x: 120
      y: 100
      z: 120
      yaw: 180
      pitch: 180
  1:
    world: 'world'
      x: 150
      y: 100
      z: 150
      yaw: 180
      pitch: 180